version: "2"
services:
  kafka:
    image: docker.io/apache/kafka:4.3.1@sha256:77e3df9054047a88b520d0cc46e16696d3b22022e1d580aeccd2632df6532837
    ports:
      - "9092:9092"
    environment:
      # KRaft settings
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      # Listeners
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=3
  seaweedfs:
    image: chrislusf/seaweedfs:4.42@sha256:f7cbc8bdbbf60a1aaba7d61784a3bdff3ec1e0657f6ad0b26d5b6ab2cd9d0dc6
    container_name: seaweedfs
    restart: unless-stopped
    command: >
      mini
      -dir=/data
      -s3
      -s3.port=8333
      -s3.config=/etc/seaweedfs/s3-config.json
      -volume.fileSizeLimitMB=1024
      -master.volumeSizeLimitMB=5000
    ports:
      # - "9333:9333" # Master UI
      # - "9340:9340" # Volume Server
      # - "8888:8888" # Filer UI
      # - "7333:7333" # WebDAV
      - "8333:8333" # S3 Endpoint
      # - "8181:8181" # Iceberg Catalog
      - "23646:23646" # Admin UI
    volumes:
      - seaweed_data:/data:rw
      # Location on disk of the S3 username/password (current directory docker-compose-s3-config.json)
      - ./docker-compose-s3-config.json:/etc/seaweedfs/s3-config.json:ro


  redis:
    image: redis:8.10-alpine@sha256:978f0e01593e65eed801f2402944efcd936d43b5027e4908a7897baf88ed6241
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - redis_data:/data

volumes:
  seaweed_data:
    driver: local
  kafka_data:
    driver: local
  redis_data:
    driver: local
